services:
  db:
    image: postgres:bullseye
    container_name: mbt_db
    environment:
      POSTGRES_DB: mbt_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: MbTC0nsulting!
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: elestio/pgadmin:REL-9_3
    restart: always
    container_name: mbt_db_web
    environment:
      PGADMIN_DEFAULT_EMAIL: ychazot@mbt-consulting.com
      PGADMIN_DEFAULT_PASSWORD: MbTC0nsulting!
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  app:
    build: .
    container_name: mbt_app
    ports:
      - "7860:7860"
    env_file:
      - app/.env
    volumes:
      - ./app:/app
      - ./shared_files:/app/emails
    depends_on:
      - db
  
  glpi:
    image: glpi/glpi:latest
    container_name: glpi
    ports:
      - "8082:80"  # GLPI accessible sur ce port
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: MbTC0nsulting!
      DB_NAME: glpi_db
    depends_on:
      - db
    volumes:
      - ./glpi_files:/var/www/html/files
      - ./glpi_config:/var/www/html/config
